#!/usr/bin/env python
"""Regenerate docs/OPEN.md -- the derived ledger of what is scientifically open right now.

The project has no live answer to "what is open". DECISIONS.md is an append-only archive
of ~37k lines, docs/plans/*.md are frozen logs, and the project memory is agent-only. Any
hand-written "what stays open" section rots the way the plans did. So this ledger is
*derived*, from the only two machine-checkable signals of open work the repo carries:

1. **Tests marked xfail/skip.** An xfail here states what is true of a source and false of
   the model, so it fails today for a stated reason and turns green when the model is fixed.
   Every `pytest.mark.xfail` / `skip` / `skipif` under `tests/` is listed with its reason and
   the D-records the reason names. Calls to `pytest.xfail()` / `pytest.skip()` *inside* a
   test body are conditional and not open hurdles; they are listed separately so nothing is
   hidden (count and print your skips).
2. **`**Flags:** D-N — clause` markers in DECISIONS.md.** A flag means a reversal is agreed
   but NOT yet in the code. Each (flagging record, target) pair is one open item. A later
   record retires a flag with `**Unflags:** D-F — clause` (every flag D-F declared) or
   `**Unflags:** D-F on D-T[, D-U] — clause` (only D-F's flags on those targets). An
   Unflags must postdate D-F and D-F must actually declare the flag it retires; otherwise the
   tool refuses, exit 2, the way gen_decisions_toc.py refuses a wrapped heading.

What the ledger is NOT: it does not read prose. An item absent here is not proven closed,
and an owner-gated build that exists only as prose does not appear. The `Corrects:` marker
is a shipped fix and plays no part.

    uv run python tools/gen_open_ledger.py          # rewrite docs/OPEN.md
    uv run python tools/gen_open_ledger.py --check  # exit 1 if stale (CI-able)

Wholly generated. Idempotent. HEADING / MARKER / slug / shorten / body_without_index are
gen_decisions_toc's, loaded by path (tools/ is not a package) so there is one definition.
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import pathlib
import re
import sys
from dataclasses import dataclass
from types import ModuleType
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parent.parent
DECISIONS = ROOT / "docs" / "DECISIONS.md"
OPEN = ROOT / "docs" / "OPEN.md"
TESTS = ROOT / "tests"
TOC_TOOL = pathlib.Path(__file__).resolve().with_name("gen_decisions_toc.py")


def _load_toc() -> ModuleType:
    spec = importlib.util.spec_from_file_location("gen_decisions_toc", TOC_TOOL)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


# A path-loaded module is untyped as far as mypy is concerned; the attributes lifted off
# it are pinned to their real types here so nothing below leaks `Any`.
toc: Any = _load_toc()
HEADING: re.Pattern[str] = toc.HEADING
MARKER: re.Pattern[str] = toc.MARKER

# `**Unflags:** D-F — clause` or `**Unflags:** D-F on D-T[, D-U] — clause`. Same shape as
# MARKER: one physical line, an em dash, a clause. Defined beside MARKER in the index
# generator (it annotates retired rows there) so the grammar has one home.
UNFLAGS: re.Pattern[str] = toc.UNFLAGS

# Anything that *looks* like a marker. Lines matching this but neither MARKER nor UNFLAGS
# (e.g. `**Flags:** D-164 §6 — ...`) are invisible to the index and to this ledger; they
# are counted and printed rather than silently dropped.
MARKER_SHAPED = re.compile(r"^\*\*(Corrects|Flags|Unflags):\*\*.*$", re.MULTILINE)

D_NUMBER = re.compile(r"D-(\d+)")

BANNER = (
    "<!-- GENERATED by tools/gen_open_ledger.py -- do not edit by hand.\n"
    "     Regenerate: uv run python tools/gen_open_ledger.py   "
    "(`--check` exits 1 when stale; run it in CI) -->"
)

DECORATOR_KINDS = ("xfail", "skip", "skipif")
BODY_KINDS = ("xfail", "skip")
# Attribute-chain tails, so `pytest.mark.xfail.foo` (4 parts) is not mistaken for a mark.
KIND_TAILS = tuple((kind,) for kind in DECORATOR_KINDS)
BODY_TAILS = tuple((kind,) for kind in BODY_KINDS)


class LedgerError(Exception):
    """A marker the ledger refuses to build on (exit 2 from the CLI)."""


@dataclass(frozen=True)
class Record:
    number: int
    title: str
    anchor: str

    @property
    def label(self) -> str:
        return f"D-{self.number}"


@dataclass(frozen=True)
class Flag:
    source: int  # the record declaring the flag
    target: int  # the record flagged
    clause: str


@dataclass(frozen=True)
class Retired:
    flag: Flag
    retired_by: int
    clause: str


@dataclass(frozen=True)
class Archive:
    records: dict[int, Record]
    open_flags: list[Flag]
    retired: list[Retired]
    unparsed: list[tuple[int | None, str]]  # (record it sits in, the line)


@dataclass(frozen=True)
class TestMarker:
    file: str  # repo-relative, posix
    line: int  # the decorator's line, where a grep lands
    name: str
    kind: str  # xfail / skip / skipif
    strict: bool | None
    reason: str
    records: tuple[str, ...]  # D-numbers the reason names, in order
    benchmark: bool

    @property
    def kind_label(self) -> str:
        return "strict xfail" if self.kind == "xfail" and self.strict else self.kind


@dataclass(frozen=True)
class BodySkip:
    file: str
    line: int
    name: str
    kind: str  # xfail / skip
    reason: str


# --------------------------------------------------------------------------- archive


def _record_at(positions: list[tuple[int, int]], offset: int) -> int | None:
    """The record whose heading is nearest above `offset`, or None before the first."""
    found: int | None = None
    for start, number in positions:
        if start > offset:
            break
        found = number
    return found


def parse_archive(body: str) -> Archive:
    """Records, open flags and retired flags, or raise LedgerError on a bad marker.

    `body` is the archive with the generated index removed (`body_without_index`).
    """
    records: dict[int, Record] = {}
    positions: list[tuple[int, int]] = []
    for match in HEADING.finditer(body):
        label, number, title = match.group(1), int(match.group(2)), match.group(3)
        records[number] = Record(number, title, str(toc.slug(f"{label} — {title}")))
        positions.append((match.start(), number))
    positions.sort()

    def check_target(kind: str, source: int, target: int) -> None:
        if target not in records:
            raise LedgerError(f"D-{source} {kind} D-{target}, which does not exist")
        # A record may FLAG its own section -- "identified here, deliberately not shipped"
        # (D-164..D-167 each do) -- but nothing may flag or unflag a LATER record, and an
        # Unflags on itself would retire a flag the same record declares.
        if target > source or (target == source and kind != "flags"):
            raise LedgerError(
                f"D-{source} {kind} D-{target}, which is not an earlier record -- a marker "
                "retires history, it cannot pre-empt it"
            )

    flags: list[Flag] = []
    for match in MARKER.finditer(body):
        if match.group(1) != "Flags":
            continue
        source = _record_at(positions, match.start())
        if source is None:
            raise LedgerError("a Flags marker appeared before any D-heading")
        for number in D_NUMBER.findall(match.group(2)):
            target = int(number)
            check_target("flags", source, target)
            flags.append(Flag(source, target, match.group(3).strip()))

    retired: list[Retired] = []
    unflags = sorted(
        ((m, _record_at(positions, m.start())) for m in UNFLAGS.finditer(body)),
        key=lambda pair: (pair[1] if pair[1] is not None else -1, pair[0].start()),
    )
    still_open = list(flags)
    for match, source in unflags:
        if source is None:
            raise LedgerError("an Unflags marker appeared before any D-heading")
        flagger = int(match.group(1).removeprefix("D-"))
        check_target("unflags", source, flagger)
        declared = [flag for flag in flags if flag.source == flagger]
        if not declared:
            raise LedgerError(
                f"D-{source} unflags D-{flagger}, but D-{flagger} declares no `**Flags:**`"
            )
        if match.group(2):
            targets = [int(n) for n in D_NUMBER.findall(match.group(2))]
            for target in targets:
                if not any(flag.target == target for flag in declared):
                    raise LedgerError(
                        f"D-{source} unflags D-{flagger} on D-{target}, but D-{flagger} "
                        f"never flagged D-{target} (it flags "
                        f"{', '.join(f'D-{f.target}' for f in declared)})"
                    )
            retiring = [flag for flag in declared if flag.target in targets]
        else:
            retiring = declared
        for flag in retiring:
            if flag not in still_open:
                already = next(r.retired_by for r in retired if r.flag == flag)
                raise LedgerError(
                    f"D-{source} unflags D-{flagger}'s flag on D-{flag.target}, which "
                    f"D-{already} already retired"
                )
            still_open.remove(flag)
            retired.append(Retired(flag, source, match.group(3).strip()))

    unparsed = [
        (_record_at(positions, m.start()), m.group(0))
        for m in MARKER_SHAPED.finditer(body)
        if not MARKER.match(m.group(0)) and not UNFLAGS.match(m.group(0))
    ]
    return Archive(records, still_open, retired, unparsed)


# --------------------------------------------------------------------------- tests


def _attr_chain(node: ast.expr) -> tuple[str, ...] | None:
    """`pytest.mark.xfail` -> ("pytest", "mark", "xfail"); None for anything else."""
    parts: list[str] = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
        return tuple(reversed(parts))
    return None


def _module_strings(tree: ast.Module) -> dict[str, str]:
    """Module-level `NAME = "..."` (or a `+` of literals), for resolving `reason=NAME`."""
    consts: dict[str, str] = {}
    for node in tree.body:
        target: ast.expr | None = None
        value: ast.expr | None = None
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target, value = node.targets[0], node.value
        elif isinstance(node, ast.AnnAssign):
            target, value = node.target, node.value
        if isinstance(target, ast.Name) and value is not None:
            text = _string_of(value, {})
            if text is not None:
                consts[target.id] = text
    return consts


def _string_of(node: ast.expr, consts: dict[str, str]) -> str | None:
    """A reason expression as text: literals (adjacent ones are already one Constant),
    `+` of literals, a Name resolved through `consts` (else the bare name), an f-string
    unparsed. None when the node is not string-shaped at all."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        left, right = _string_of(node.left, consts), _string_of(node.right, consts)
        return None if left is None or right is None else left + right
    if isinstance(node, ast.Name):
        return consts.get(node.id, node.id)
    if isinstance(node, ast.JoinedStr):
        return ast.unparse(node)
    return None


def _reason_of(call: ast.Call | None, consts: dict[str, str], positional: bool) -> str:
    """`reason=` keyword, else the first positional when the call's first argument IS the
    reason (`pytest.mark.skip("why")`, `pytest.skip("why")`); "" for a bare mark."""
    if call is None:
        return ""
    for keyword in call.keywords:
        if keyword.arg == "reason":
            return _string_of(keyword.value, consts) or ast.unparse(keyword.value)
    if positional and call.args:
        return _string_of(call.args[0], consts) or ast.unparse(call.args[0])
    return ""


def _strict_of(call: ast.Call | None) -> bool | None:
    if call is None:
        return None
    for keyword in call.keywords:
        if keyword.arg == "strict" and isinstance(keyword.value, ast.Constant):
            return bool(keyword.value.value)
    return None


def _mark_kind(decorator: ast.expr) -> tuple[str, ast.Call | None] | None:
    call = decorator if isinstance(decorator, ast.Call) else None
    chain = _attr_chain(call.func if call is not None else decorator)
    if chain is not None and chain[:2] == ("pytest", "mark") and chain[2:] in KIND_TAILS:
        return chain[2], call
    return None


def _records_in(reason: str) -> tuple[str, ...]:
    seen: list[str] = []
    for number in D_NUMBER.findall(reason):
        label = f"D-{number}"
        if label not in seen:
            seen.append(label)
    return tuple(seen)


def _walk_bodies(node: ast.AST, stack: list[str], out: list[tuple[str, ast.Call, str]]) -> None:
    """Every `pytest.xfail(...)` / `pytest.skip(...)` call, with its innermost enclosing
    function ("<module>" when there is none)."""
    if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
        stack.append(node.name)
        for child in ast.iter_child_nodes(node):
            _walk_bodies(child, stack, out)
        stack.pop()
        return
    if isinstance(node, ast.Call):
        chain = _attr_chain(node.func)
        if chain is not None and chain[:1] == ("pytest",) and chain[1:] in BODY_TAILS:
            out.append((stack[-1] if stack else "<module>", node, chain[1]))
    for child in ast.iter_child_nodes(node):
        _walk_bodies(child, stack, out)


def collect_test_markers(
    tests_root: pathlib.Path = TESTS, root: pathlib.Path = ROOT
) -> tuple[list[TestMarker], list[BodySkip]]:
    """Walk `tests/**/*.py` with `ast`; no test module is imported."""
    markers: list[TestMarker] = []
    body_skips: list[BodySkip] = []
    files = sorted(path for path in tests_root.rglob("*.py") if "__pycache__" not in path.parts)
    for path in files:
        rel = path.relative_to(root).as_posix()
        benchmark = rel.startswith("tests/benchmarks/")
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=rel)
        consts = _module_strings(tree)

        decorated = [
            node
            for node in ast.walk(tree)
            if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef)
        ]
        for node in decorated:
            for decorator in node.decorator_list:
                found = _mark_kind(decorator)
                if found is None:
                    continue
                kind, call = found
                reason = _reason_of(call, consts, positional=kind == "skip")
                markers.append(
                    TestMarker(
                        file=rel,
                        line=decorator.lineno,
                        name=node.name,
                        kind=kind,
                        strict=_strict_of(call),
                        reason=reason,
                        records=_records_in(reason),
                        benchmark=benchmark,
                    )
                )
        # A module-wide `pytestmark = pytest.mark.skip(...)` marks every test in the file.
        for stmt in tree.body:
            if (
                isinstance(stmt, ast.Assign)
                and len(stmt.targets) == 1
                and isinstance(stmt.targets[0], ast.Name)
                and stmt.targets[0].id == "pytestmark"
            ):
                values = stmt.value.elts if isinstance(stmt.value, ast.List) else [stmt.value]
                for value in values:
                    found = _mark_kind(value)
                    if found is None:
                        continue
                    kind, call = found
                    reason = _reason_of(call, consts, positional=kind == "skip")
                    markers.append(
                        TestMarker(
                            file=rel,
                            line=stmt.lineno,
                            name="<module>",
                            kind=kind,
                            strict=_strict_of(call),
                            reason=reason,
                            records=_records_in(reason),
                            benchmark=benchmark,
                        )
                    )

        calls: list[tuple[str, ast.Call, str]] = []
        _walk_bodies(tree, [], calls)
        for name, call, kind in calls:
            body_skips.append(
                BodySkip(rel, call.lineno, name, kind, _reason_of(call, consts, positional=True))
            )

    markers.sort(key=lambda m: (not m.benchmark, m.file, m.line))
    body_skips.sort(key=lambda b: (b.file, b.line))
    return markers, body_skips


# --------------------------------------------------------------------------- rendering


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|") or "—"


def _link(archive: Archive, label: str) -> str:
    record = archive.records.get(int(label.removeprefix("D-")))
    if record is None:
        return f"{label} (no such record)"
    return f"[{label}](DECISIONS.md#{record.anchor})"


def _record_cell(archive: Archive, number: int) -> str:
    record = archive.records[number]
    return f"{_link(archive, record.label)} — {_cell(str(toc.shorten(record.title)))}"


def _file_link(file: str, line: int) -> str:
    return f"[{file}:{line}](../{file}#L{line})"


def build_ledger(archive: Archive, markers: list[TestMarker], body_skips: list[BodySkip]) -> str:
    """The whole docs/OPEN.md, from parsed inputs only."""
    kinds = {
        label: sum(1 for m in markers if m.kind_label == label)
        for label in ("strict xfail", "xfail", "skip", "skipif")
    }
    kind_summary = ", ".join(f"{n} {label}" for label, n in kinds.items() if n)
    flagged_targets = {flag.target for flag in archive.open_flags}
    benchmarks = sum(1 for m in markers if m.benchmark)

    out: list[str] = [
        BANNER,
        "",
        "# Open ledger",
        "",
        "What is scientifically open right now, **derived** — not written. This file is built "
        "from exactly two machine-checkable signals and nothing else:",
        "",
        "1. **Tests marked `xfail` / `skip` / `skipif`** under `tests/`. An xfail states what is "
        "true of a source and false of the model, so it fails today for a stated reason and "
        "turns green when the model is fixed. The D-records its reason names are linked.",
        "2. **`**Flags:** D-N — clause` markers in `DECISIONS.md`** — a reversal that is agreed "
        "but **not yet in the code**. Each (flagging record, target) pair is one open item, "
        "until a later record retires it with `**Unflags:** D-F — clause` (every flag D-F "
        "declared) or `**Unflags:** D-F on D-T — clause` (only D-F's flag on D-T).",
        "",
        'What it is **not**: it does not read prose. A "what stays open" section in a record '
        "is a breadcrumb, not a signal, and is not parsed. **An item absent here is not "
        "proven closed** — a hurdle nobody wrote a test or a flag for is invisible, and an "
        "owner-gated build that exists only as prose does not appear. `**Corrects:**` is a "
        "shipped fix and plays no part. To close a row, fix the model (the xfail turns green "
        "and strict mode forces its removal) or append a record with an `Unflags:` marker; "
        "never edit this file.",
        "",
        f"**Counts.** {len(markers)} open test markers ({kind_summary or 'none'}; "
        f"{benchmarks} in `tests/benchmarks/`). {len(archive.open_flags)} open flags on "
        f"{len(flagged_targets)} records. {len(archive.retired)} retired. "
        f"{len(body_skips)} conditional skips inside test bodies. "
        f"{len(archive.unparsed)} marker-shaped lines the parser cannot read.",
        "",
        "Regenerate with `uv run python tools/gen_open_ledger.py` (`--check` in CI).",
        "",
        "## 1. Tests that state a truth the model does not yet meet",
        "",
        "Benchmarks first, then the rest; file order, then line. `strict xfail` means a fix "
        "that turns the test green also fails the suite until the marker is removed — the "
        "closing is forced to be recorded.",
        "",
    ]
    if markers:
        out += [
            "| test | where | kind | reason | records |",
            "|---|---|---|---|---|",
        ]
        for m in markers:
            records = ", ".join(_link(archive, r) for r in m.records) or "—"
            out.append(
                f"| `{m.name}` | {_file_link(m.file, m.line)} | {m.kind_label} | "
                f"{_cell(m.reason)} | {records} |"
            )
    else:
        out.append("none — no test under `tests/` carries an xfail/skip marker.")

    out += [
        "",
        "## 2. Declared reversals not yet in the code",
        "",
        "One row per open (flagging record, target) pair, by target then flagger. The clause "
        "is verbatim from the flagging record.",
        "",
    ]
    if archive.open_flags:
        out += ["| target record | flagged by | clause |", "|---|---|---|"]
        for flag in sorted(archive.open_flags, key=lambda f: (f.target, f.source)):
            out.append(
                f"| {_record_cell(archive, flag.target)} | {_link(archive, f'D-{flag.source}')} "
                f"| {_cell(flag.clause)} |"
            )
    else:
        out.append("none — no record carries an open `**Flags:**` marker.")
    if archive.unparsed:
        out += [
            "",
            f"**{len(archive.unparsed)} marker-shaped lines the parser cannot read.** They "
            "begin with a marker word but their target list is not a plain `D-N[, D-M]` "
            "(a `§` clause, a `/`), so they carry no weight in the index or here. Rewrite "
            "them to the marker grammar, or leave them as prose; either way they are listed "
            "so they are not lost:",
            "",
        ]
        for number, line in archive.unparsed:
            where = _link(archive, f"D-{number}") if number is not None else "before D-1"
            out.append(f"- {where}: `{_cell(str(toc.shorten(line)))}`")

    out += [
        "",
        "## 3. Retired flags",
        "",
        "Pairs an `**Unflags:**` marker retired, with the retiring record.",
        "",
    ]
    if archive.retired:
        out += [
            "| target record | was flagged by | retired by | clause |",
            "|---|---|---|---|",
        ]
        for item in sorted(archive.retired, key=lambda r: (r.flag.target, r.flag.source)):
            out.append(
                f"| {_record_cell(archive, item.flag.target)} | "
                f"{_link(archive, f'D-{item.flag.source}')} | "
                f"{_link(archive, f'D-{item.retired_by}')} | {_cell(item.clause)} |"
            )
    else:
        out.append("none yet.")

    out += [
        "",
        "## 4. Conditional skips inside test bodies",
        "",
        "`pytest.skip()` / `pytest.xfail()` called from a test body. These fire on a "
        "condition, not on the model's state, so they are not open hurdles — printed so no "
        "skip goes uncounted.",
        "",
    ]
    if body_skips:
        out += ["| where | test | call | reason |", "|---|---|---|---|"]
        for b in body_skips:
            out.append(
                f"| {_file_link(b.file, b.line)} | `{b.name}` | `pytest.{b.kind}` | "
                f"{_cell(b.reason)} |"
            )
    else:
        out.append("none.")

    return "\n".join(out) + "\n"


def generate(text: str) -> str:
    """The ledger for an archive text (index block stripped here), against `tests/`."""
    archive = parse_archive(str(toc.body_without_index(text)))
    markers, body_skips = collect_test_markers()
    return build_ledger(archive, markers, body_skips)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the ledger is stale")
    args = parser.parse_args()

    try:
        ledger = generate(DECISIONS.read_text(encoding="utf-8"))
    except LedgerError as err:
        print(f"error: {err}", file=sys.stderr)
        return 2

    current = OPEN.read_text(encoding="utf-8") if OPEN.exists() else None
    summary = re.search(r"\*\*Counts\.\*\* (.+)", ledger)
    assert summary is not None  # build_ledger always writes the line
    counts = f"{ledger.count(chr(10))} lines; {summary.group(1)}"

    if args.check:
        if ledger != current:
            print("docs/OPEN.md is stale -- run: uv run python tools/gen_open_ledger.py")
            return 1
        print(f"docs/OPEN.md is current ({counts})")
        return 0

    if ledger != current:
        # newline="\n" matters: the default translates to CRLF on Windows and rewrites the
        # whole file, which .gitattributes (eol=lf) then has to undo.
        OPEN.write_text(ledger, encoding="utf-8", newline="\n")
        print(f"ledger regenerated ({counts})")
    else:
        print(f"ledger already current ({counts})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
