#!/usr/bin/env python
"""Regenerate the index block in docs/DECISIONS.md.

DECISIONS.md is the canonical archive and it gains a record most sessions, so a
hand-maintained index is a staleness bug waiting to happen -- the same class as
the "D-1 ... D-37" pointer this repo's ARCHITECTURE.md carried until D-111, and
the "D-1 ... D-50" one in the project memory. Generate it instead of typing it.

Rewrites everything between the INDEX markers, in place. Idempotent.

    uv run python tools/gen_decisions_toc.py          # rewrite the index
    uv run python tools/gen_decisions_toc.py --check  # exit 1 if stale (CI-able)
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

DECISIONS = pathlib.Path(__file__).resolve().parent.parent / "docs" / "DECISIONS.md"

BEGIN = "<!-- BEGIN INDEX (generated by tools/gen_decisions_toc.py -- do not edit by hand) -->"
END = "<!-- END INDEX -->"

# Only genuine decision records: "## D-<n> — <title>". Sub-sections inside a record
# (e.g. "### D-19 sourcing step", "### D-104's split ...") are h3 and must not match.
HEADING = re.compile(r"^## (D-(\d+)) — (.+)$", re.MULTILINE)

TITLE_MAX = 100


def slug(heading_text: str) -> str:
    """Approximate GitHub's heading-anchor algorithm."""
    s = heading_text.strip().lower()
    s = re.sub(r"[^\w\s-]", "", s, flags=re.UNICODE)
    return s.replace(" ", "-")


def shorten(title: str) -> str:
    """Trim a long title at a word boundary; the full text is at the link."""
    flat = " ".join(title.split())
    if len(flat) <= TITLE_MAX:
        return flat
    return flat[:TITLE_MAX].rsplit(" ", 1)[0].rstrip(",;:—-") + " …"


def build_index(text: str) -> tuple[str, int]:
    rows = []
    for match in HEADING.finditer(text):
        label, number, title = match.group(1), int(match.group(2)), match.group(3)
        anchor = slug(f"{label} — {title}")
        rows.append((number, f"- [**{label}**](#{anchor}) — {shorten(title)}"))

    rows.sort(key=lambda row: row[0])
    listing = "\n".join(row for _, row in rows)
    block = (
        f"{BEGIN}\n"
        f"## Index\n\n"
        f"{len(rows)} engineering decisions. Titles are trimmed; the full record is "
        f"at each link. Regenerate with `uv run python tools/gen_decisions_toc.py`.\n\n"
        f"{listing}\n"
        f"{END}"
    )
    return block, len(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the index is stale")
    args = parser.parse_args()

    text = DECISIONS.read_text(encoding="utf-8")
    index, count = build_index(text)

    if BEGIN not in text or END not in text:
        print(f"error: index markers not found in {DECISIONS}", file=sys.stderr)
        return 2

    updated = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        lambda _: index,
        text,
        flags=re.DOTALL,
    )

    if args.check:
        if updated != text:
            print("DECISIONS.md index is stale -- run: uv run python tools/gen_decisions_toc.py")
            return 1
        print("DECISIONS.md index is current")
        return 0

    if updated != text:
        DECISIONS.write_text(updated, encoding="utf-8")
        print(f"index regenerated ({count} entries)")
    else:
        print(f"index already current ({count} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
